config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  # Landing page and browsing
  root 'home#index'
  get 'browse',                           to: 'home#browse',                                  as: 'browse'
  get 'browse_healthy',                   to: 'home#browse_healthy',                          as: 'browse_healthy'
  get 'browse_with_query/:query',         to: 'home#browse_with_query',                       as: 'browse_with_query'
  get 'browse_category/:category',        to: 'home#browse_category',                         as: 'browse_category'
  get 'choose_category',                  to: 'home#choose_category',                         as: 'choose_category'
  get 'learn_more',                       to: 'home#learn_more',                              as: 'learn_more'

  # PDFs
  get 'research_participation',           to: 'home#research_participation_pdf',              as: 'research_participation'
  get 'research_participation_spanish',   to: 'home#research_participation_spanish_pdf',      as: 'research_participation_spanish'
  get 'bill_of_rights',                   to: 'home#bill_of_rights_pdf',                      as: 'bill_of_rights'
  get 'blood_draw',                       to: 'home#blood_draw_pdf',                          as: 'blood_draw'
  get 'blood_draw_spanish',               to: 'home#blood_draw_spanish_pdf',                  as: 'blood_draw_spanish'
  get 'genetic_research',                 to: 'home#genetic_research_pdf',                    as: 'genetic_research'
  get 'genetic_research_spanish',         to: 'home#genetic_research_spanish_pdf',            as: 'genetic_research_spanish'

  # Profile creation
  get  'age',                             to: 'profiles#get_age',                             as: 'age'
  post 'save_age',                        to: 'profiles#save_age',                            as: 'save_age'
  get  'healthy',                         to: 'profiles#get_healthy',                         as: 'healthy'
  post 'save_healthy',                    to: 'profiles#save_healthy',                        as: 'save_healthy'
  get  'categories',                      to: 'profiles#get_categories',                      as: 'categories'
  post 'save_categories',                 to: 'profiles#save_categories',                     as: 'save_categories'
  get  'email',                           to: 'profiles#get_email',                           as: 'email'
  post 'save_email',                      to: 'profiles#save_email',                          as: 'save_email'
  get 'profile_complete/:uuid',           to: 'profiles#profile_complete',                    as: 'profile_complete'
  get 'unsubscribe/:uuid',                to: 'profiles#unsubscribe',                         as: 'unsubscribe'

  # Admin
  post 'update_verified/:id',             to: 'admin#update_verified',                        as: 'update_verified'
  post 'update_category/:id',             to: 'admin#update_category',                        as: 'update_category'
  get 'edit_trials',                      to: 'admin#edit_trials',                            as: 'edit_trials'
  get 'edit_trial/:id',                   to: 'dartmouth_clinical_trials#edit',               as: 'edit_trial'
  get 'show_trial/:id',                   to: 'dartmouth_clinical_trials#show',               as: 'show_trial'
  post 'update_trial',                    to: 'dartmouth_clinical_trials#update',             as: 'update_trial'
  get 'admin',                            to: 'admin#index',                                  as: 'admin'  
  get 'search',                           to: 'admin#search',                                 as: 'search'
  post 'search_results',                  to: 'admin#search_results',                         as: 'search_results'
  post 'user_email',                      to: 'admin#user_email',                             as: 'user_email'

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  has_many :trial_notifications

  validates_uniqueness_of :email
  validates :csv_categories, :age, :email, :uuid, presence: true
  validates :healthy, :active, inclusion: [true, false]

  scope :active, -> { where(active: true) }

  # All dartmouth_clinical_trials that match this profile
  # NOTE: Slick but brittle. Profile.age values much have a corresponding scope in the DartmouthClinicalTrial model
  def trials
    if healthy
      DartmouthClinicalTrial.recruiting.send(age).where("category in (?) or healthy_volunteers=true", categories).all
    else
      DartmouthClinicalTrial.recruiting.send(age).where(category: categories).all
    end
  end

  # All dartmouth_clinical_trials that both match this profile and have not had a notification sent
  def trials_needing_notification
    trials.where.not(id: TrialNotification.select('dartmouth_clinical_trial_id').where(profile_id: id)).all
  end

  # Returns an array of category strings. Should all be members of DartmouthClinicalTrial.categories
  def categories
    csv_categories.split(',')
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  skip_before_filter :auth_user

  # Form asking age range preference
  def get_age
    session['profile'] = {} unless session['profile'].present?
    @age = session['profile']['age']
  end

  # Store age range preference in session
  def save_age
    if profile_params[:age].present?
      session['profile']['age'] = profile_params[:age]
      redirect_to healthy_path
    else
      redirect_to age_path
    end
  end

  # Form asking healthy volunteers question
  def get_healthy
    redirect_to age_path unless session['profile']['age'].present?
    @healthy = session['profile']['healthy']
  end

  # Store healthy volunteers preference in session
  def save_healthy
    if profile_params[:healthy].present?
      session['profile']['healthy'] = profile_params[:healthy]
      redirect_to categories_path
    else
      redirect_to healthy_path
    end
  end

  # Form asking trial categories question
  def get_categories
    redirect_to healthy_path unless session['profile']['healthy'].present?
    @categories = session['profile']['categories']
    # Splitting categories for two-column display
    categories = DartmouthClinicalTrial.categories
    @categories_first_half = categories[0, categories.length / 2]
    @categories_second_half = categories[categories.length / 2, categories.length]
  end

  # Store trial category preferences in session
  def save_categories
    # Can't use strong parameters here without duplicating the whole category list
    # So, test each key for inclusion in the category list before adding it
    if params[:categories].present?
      all_categories = DartmouthClinicalTrial.categories
      categories = [] 
      params[:categories].keys.each do |category|
        categories << category if all_categories.include?(category)
      end
      session['profile']['categories'] = categories
      redirect_to email_path
    else
      redirect_to categories_path
    end
  end

  # Form asking for profile email address
  def get_email
    redirect_to categories_path unless session['profile']['categories'].present?
    @email = session['profile']['email']
  end

  # Store profile email in session and redirect to create profile record
  def save_email
    if profile_params[:email].present?
      session['profile']['email'] = profile_params[:email]
      create
    else
      redirect_to email_path
    end
  end

  # Displayed upon successful profile creation
  def profile_complete
    @profile = Profile.where(uuid: params[:uuid]).first
    @trials = @profile.trials
    UserMailer.new_profile(@profile).deliver_later!(wait: 10.seconds)
  end

  # Unsubscribe profile from future emails
  def unsubscribe
    profile = Profile.where(uuid: params[:uuid]).first
    profile.update_attributes(active: false) if profile
    # Redirect back if profile was unsubscribed by an admin
    if current_user and current_user.admin?
      flash.notice = "#{profile.email} has been unsubscribed"
      redirect_to :back
      return
    end
  end

  private

  def profile_params
    params.permit(
      :age,
      :healthy,
      :email
    )
  end

  # Create profile record
  def create
    profile = Profile.new
    profile.age = session['profile']['age']
    profile.healthy = {'yes': true, 'no': false}[session['profile']['healthy'].to_sym] if session['profile']['healthy']
    profile.email = session['profile']['email']
    profile.csv_categories = session['profile']['categories'].join(',')
    profile.uuid = SecureRandom.hex(30)
    if profile.save
      # Successful save. Clear the profile parameters from the session
      session['profile'] = {}
      redirect_to profile_complete_path(uuid: profile.uuid)
    else
      flash.alert = profile.errors.full_messages
      redirect_to email_path
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_intro_text.html.haml
#intro-text Here you can sign up to receive email alerts about clinical trials at Dartmouth-Hitchcock. You can choose the kinds of studies that interest you, and you will receive email alerts when matching studies are recruiting. You can unsubscribe from these alerts at any time.

app/views/profiles/get_age.html.haml
.body-container
  .row
    .col-md-2
    .col-md-8
      = render 'intro_text'
      .profile-question
        .text-center.text-gray Question 1 of 4
        %h4.question Are you interested in studies that require adults, minors, or both?
        %div{style: 'margin-top:30px;'}
          = form_tag save_age_path, class: 'form-inline' do
            %div{style: 'margin-left:20px;'}
              = radio_button_tag 'age', 'adults', @age == 'adults', class: 'age-radio-button'
              = label_tag 'age_adults', 'Adults'
            %div{style: 'margin-left:20px;'}
              = radio_button_tag 'age', 'minors', @age == 'minors', class: 'age-radio-button'
              = label_tag 'age_minors', 'Minors'
            %div{style: 'margin-left:20px;'}
              = radio_button_tag 'age', 'both', @age == 'both', class: 'age-radio-button'
              = label_tag 'age_both', 'Both'
            - display = 'none'
            - display = 'inline' if @age
            .row.centered{style: 'text-align:center;margin-top:20px'}
              = link_to 'Back', root_path, class: 'btn blue-btn' 
              = submit_tag  'Continue', style: "display:#{display};", class: 'btn blue-btn conditional-submit-display', id: 'age-submit'
    .col-md-2

app/views/profiles/get_categories.html.haml
.body-container
  .row
    .col-md-1
    .col-md-10
      = render 'intro_text'
      .profile-question
        .text-center.text-gray Question 3 of 4
        %h4.question Please choose the categories to receive alerts about.
        %div{style: 'margin-top:30px;'}
          = form_tag save_categories_path, class: 'form-inline' do
            .row
              .col-md-6{style: 'padding-left:30px;'}
                - @categories_first_half.each do |category|
                  = check_box_tag "categories[#{category}]", category, @categories && @categories.include?(category), class: 'category-checkbox'
                  = label_tag "categories[#{category}]", category
                  %br
              .col-md-6{style: 'padding-left:30px;'}
                - @categories_second_half.each do |category|
                  = check_box_tag "categories[#{category}]", category, @categories && @categories.include?(category), class: 'category-checkbox'
                  = label_tag "categories[#{category}]", category
                  %br
            - display = 'none'
            - display = 'inline' if @categories
            .row.centered{style: 'text-align:center;margin-top:20px'}
              = link_to 'Back', healthy_path, class: 'btn blue-btn'
              = submit_tag  'Continue', style: "display:#{display};", class: 'btn blue-btn conditional-submit-display', id: 'categories-submit'
    .col-md-1

:javascript
  $(function() {
    if("#{session['profile']['healthy']}" == 'yes') {
      $("#categories_Healthy___Prevention").prop('checked', true);
    };
    categoryCheckboxes();
  })

app/views/profiles/get_email.html.haml
.body-container
  .row
    .col-md-2
    .col-md-8
      = render 'intro_text'
      .profile-question
        .text-center.text-gray Question 4 of 4
        %h4.question What email address would you like to receive alerts at?
        %div{style: 'margin-top:30px;'}
          = form_tag save_email_path, class: 'form-inline', size: '35', autocomplete: 'off' do
            %div{style: 'margin-left:20px;'}
              = email_field_tag 'email', nil, size: '35', id: 'profile-email', style: 'color:black;padding:5px;', autocomplete: 'off', autofocus: 'true'
              %br
              = label_tag 'email', 'Email Address'
            - display = 'none'
            .row.centered{style: 'text-align:center;margin-top:20px'}
              = link_to 'Back', categories_path, class: 'btn blue-btn'
              = submit_tag  'Complete Signup', style: "display:#{display};", class: 'btn blue-btn', id: 'email-submit'
    .col-md-2

app/views/profiles/get_healthy.html.haml
.body-container
  .row
    .col-md-2
    .col-md-8
      = render 'intro_text'
      .profile-question
        .text-center.text-gray Question 2 of 4
        %h4.question Are you interested in studies that require healthy volunteers?
        %div{style: 'margin-top:30px;'}
          = form_tag save_healthy_path, class: 'form-inline' do
            %div{style: 'margin-left:20px;'}
              = radio_button_tag 'healthy', 'yes', @healthy == 'yes', class: 'healthy-radio-button'
              = label_tag 'healthy_yes', 'Yes'
            %div{style: 'margin-left:20px;'}
              = radio_button_tag 'healthy', 'no', @healthy == 'no', class: 'healthy-radio-button'
              = label_tag 'healthy_no', 'No'
            - display = 'none'
            - display = 'inline' if @healthy
            .row.centered{style: 'text-align:center;margin-top:20px'}
              = link_to 'Back', age_path, class: 'btn blue-btn'
              = submit_tag  'Continue', style: "display:#{display};", class: 'btn blue-btn conditional-submit-display', id: 'healthy-submit'
    .col-md-2

app/views/profiles/profile_complete.html.haml
.body-container
  #profile-complete
    #intro-text{style: 'color:black;'}
      - if @trials.first
        %p Success! We have saved your preferences. Below is a list of currently recruiting studies that match your preferences. You will receive a confirmation email soon that will allow you to receive alerts as new studies become available.
      - else
        %p Success! We have saved your preferences. Currently, there are no recruiting studies that match your preferences. You will receive a confirmation email soon that will allow you to receive alerts as new studies become available.
      %p Thank you for registering!
      %p= link_to 'Return to home page', root_path, class: 'btn blue-btn'
      - if @trials.first
        %p Click on a trial for more details.
    - if @trials.first
      .row{style: 'margin-top:35px;'}
        .col-xs-12
          - if @profile.healthy
            = star
            = '= Accepting healthy volunteers'
          %table.table
            %thead
              %tr
                %th.small Category
                %th.small Title
              %tbody
                - @trials.each do |trial|
                  %tr.trial-title
                    %td.small
                      %span.trial-chevron.fa.fa-chevron-circle-right 
                      .table-cell= trial.category
                    %td.small
                      = star if trial.category.downcase.include?('healthy') || trial.healthy_volunteers
                      = trial.title || 'No Title'
                  %tr.trial-details
                    %td.small{colspan: '2', style: 'border-top:none;'}
                      %p
                        %strong Contact Email: 
                        = mail_to (trial.contact_email || 'admin@engage.dartmouth.edu')
                      %p
                        %strong Summary: 
                        = trial.summary
                      %p
                        %strong Gender:
                        = trial.gender
                      %p
                        %strong Minimum Age:
                        = trial.min_age || 'None'
                      %p
                        %strong Maximum Age:
                        = trial.max_age || 'None'
                      %p
                        %strong Needs Healthy Volunteers:
                        = {true: 'Yes', false: 'No'}[trial.healthy_volunteers.to_s.to_sym]

app/views/profiles/unsubscribe.html.haml
.body-container
  .row
    .col-sm-2
    .col-sm-8
      %h3#unsubscribe.background-white
        You have been unsubscribed. You will no longer receieve emails regarding opportunities to 
        participate in clinical trials at Dartmouth-Hitchcock.
    .col-sm-2