config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  # Landing page and browsing
  root 'home#index'
  get 'browse',                           to: 'home#browse',                                  as: 'browse'
  get 'browse_healthy',                   to: 'home#browse_healthy',                          as: 'browse_healthy'
  get 'browse_with_query/:query',         to: 'home#browse_with_query',                       as: 'browse_with_query'
  get 'browse_category/:category',        to: 'home#browse_category',                         as: 'browse_category'
  get 'choose_category',                  to: 'home#choose_category',                         as: 'choose_category'
  get 'learn_more',                       to: 'home#learn_more',                              as: 'learn_more'

  # PDFs
  get 'research_participation',           to: 'home#research_participation_pdf',              as: 'research_participation'
  get 'research_participation_spanish',   to: 'home#research_participation_spanish_pdf',      as: 'research_participation_spanish'
  get 'bill_of_rights',                   to: 'home#bill_of_rights_pdf',                      as: 'bill_of_rights'
  get 'blood_draw',                       to: 'home#blood_draw_pdf',                          as: 'blood_draw'
  get 'blood_draw_spanish',               to: 'home#blood_draw_spanish_pdf',                  as: 'blood_draw_spanish'
  get 'genetic_research',                 to: 'home#genetic_research_pdf',                    as: 'genetic_research'
  get 'genetic_research_spanish',         to: 'home#genetic_research_spanish_pdf',            as: 'genetic_research_spanish'

  # Profile creation
  get  'age',                             to: 'profiles#get_age',                             as: 'age'
  post 'save_age',                        to: 'profiles#save_age',                            as: 'save_age'
  get  'healthy',                         to: 'profiles#get_healthy',                         as: 'healthy'
  post 'save_healthy',                    to: 'profiles#save_healthy',                        as: 'save_healthy'
  get  'categories',                      to: 'profiles#get_categories',                      as: 'categories'
  post 'save_categories',                 to: 'profiles#save_categories',                     as: 'save_categories'
  get  'email',                           to: 'profiles#get_email',                           as: 'email'
  post 'save_email',                      to: 'profiles#save_email',                          as: 'save_email'
  get 'profile_complete/:uuid',           to: 'profiles#profile_complete',                    as: 'profile_complete'
  get 'unsubscribe/:uuid',                to: 'profiles#unsubscribe',                         as: 'unsubscribe'

  # Admin
  post 'update_verified/:id',             to: 'admin#update_verified',                        as: 'update_verified'
  post 'update_category/:id',             to: 'admin#update_category',                        as: 'update_category'
  get 'edit_trials',                      to: 'admin#edit_trials',                            as: 'edit_trials'
  get 'edit_trial/:id',                   to: 'dartmouth_clinical_trials#edit',               as: 'edit_trial'
  get 'show_trial/:id',                   to: 'dartmouth_clinical_trials#show',               as: 'show_trial'
  post 'update_trial',                    to: 'dartmouth_clinical_trials#update',             as: 'update_trial'
  get 'admin',                            to: 'admin#index',                                  as: 'admin'  
  get 'search',                           to: 'admin#search',                                 as: 'search'
  post 'search_results',                  to: 'admin#search_results',                         as: 'search_results'
  post 'user_email',                      to: 'admin#user_email',                             as: 'user_email'

end

app/views/admin/_profile_detail.html.haml
.col-xs-8.col-xs-offset-2.pad-20
  = "Send email to #{profile.user.email}"
  = bootstrap_form_tag url: user_email_path do |f|
    = f.hidden_field :email, value: profile.user.email
    = f.text_field :subject
    = f.text_area :body, rows: 10
    = submit_tag 'Send', class: 'btn btn-primary'

app/views/admin/edit_trials.html.haml
.row
  .col-xs-12
    %p Click on a trial title to enable full trial editing.
    .panel.panel-default.table-responsive{style: 'overflow:auto;'}
      %table.table.table-striped
        %thead
          %tr
            %th.small Verified
            %th.small Category
            %th.small Title
            %th.small Conditions
            %th.small Keywords
            %th.small MeSH terms
        %tbody
          - @trials.each do |trial|
            %tr
              %td.small.text-center= check_box_tag nil, trial.verified, trial.verified, class: 'verified-check-box', id: trial.id 
              %td.small= select_tag 'category', options_for_select(DartmouthClinicalTrial.categories, trial.category), class: 'category-select', id: trial.id, include_blank: true
              %td.small= link_to trial.title, edit_trial_path(trial.id)
              %td.small= [trial.condition_1, trial.condition_2, trial.condition_3, trial.condition_4, trial.condition_5].join('<br>').html_safe
              %td.small= [trial.keyword_1, trial.keyword_2, trial.keyword_3, trial.keyword_4, trial.keyword_5].join('<br>').html_safe
              %td.small= [trial.mesh_term_1, trial.mesh_term_2, trial.mesh_term_3, trial.mesh_term_4, trial.mesh_term_5].join('<br>').html_safe

app/views/admin/index.html.haml
%h3
  %span.green-badge= @trials.length
  recruiting trials, 
  %span.green-badge= @profiles.length
  subscribers
.row{style: 'margin-top:35px;'}
  .col-xs-12
    %table.table.sorted-table
      %thead
        %tr
          %th.bigger Email
          %th.bigger Age
          %th.bigger Categories
          %th.bigger Current Matches
          %th.bigger Unsubscribe
        %tbody
          - @profiles.each do |profile|
            %tr
              %td.bigger= mail_to profile.email
              %td.bigger= profile.age.humanize
              %td.bigger= profile.csv_categories.gsub(',', '<br>').html_safe
              %td.bigger
                - trials = profile.trials
                %p.trials-count= link_to trials.count
                %p.profile-trials{style: 'display:none;'}
                  - profile.trials.each do |trial|
                    = link_to trial.nct_id, show_trial_path(trial.id)
                    %br
              %td.bigger{style: 'padding-top:12px;'}
                = link_to 'Unsubscribe',
                  unsubscribe_path(profile.uuid),
                  class: 'btn, green-btn',
                  data: {confirm: "Are you sure that you want to unsubscribe #{profile.email}?"},
                  style: 'padding:8px;'

app/views/admin/search.html.haml
%h3 Recruiting Dartmouth clinical trials.

- if @search
  %p
    = "Found #{@trials.length} trials matching \"#{@query}\". "
    = link_to 'Clear search', search_path
- else
  %p= "Found #{@trials.length} recruiting trials."

.row
  = bootstrap_form_tag url: search_results_path, class: 'form-horizontal', role: 'form' do |f|
    .col-md-2
      = f.text_field :query, hide_label: true
    .col-md-2
      = f.submit 'Search', class: 'btn green-btn', style: 'padding:8px;'

.row
  .col-xs-12
    .panel.panel-default.table-responsive{style: 'overflow:auto;'}
      %table.table.table-striped
        %thead
          %tr
            %th Category
            %th Title
            %th NCT ID
            %th Sponsor
            %th Study offcial
            %th Contact name
            %th Contact email
            %th Contact phone
            %th Start date
            %th End date
            %th Conditions
            %th Keywords
            %th MeSH terms
        %tbody
          - @trials.each do |trial|
            %tr
              %td= trial.category
              %td= trial.title
              %td= link_to trial.nct_id, "https://clinicaltrials.gov/ct2/show/#{trial.nct_id}"
              %td= trial.sponsor
              %td= trial.title
              %td= trial.contact_name
              %td= trial.contact_email
              %td= trial.contact_phone
              %td= trial.start_date.strftime("%m/%d/%y") if trial.start_date
              %td= trial.end_date.strftime("%m/%d/%y") if trial.end_date
              %td= [trial.condition_1, trial.condition_2, trial.condition_3, trial.condition_4, trial.condition_5].join('<br>').html_safe
              %td= [trial.keyword_1, trial.keyword_2, trial.keyword_3, trial.keyword_4, trial.keyword_5].join('<br>').html_safe
              %td= [trial.mesh_term_1, trial.mesh_term_2, trial.mesh_term_3, trial.mesh_term_4, trial.mesh_term_5].join('<br>').html_safe