config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  # Landing page and browsing
  root 'home#index'
  get 'browse',                           to: 'home#browse',                                  as: 'browse'
  get 'browse_healthy',                   to: 'home#browse_healthy',                          as: 'browse_healthy'
  get 'browse_with_query/:query',         to: 'home#browse_with_query',                       as: 'browse_with_query'
  get 'browse_category/:category',        to: 'home#browse_category',                         as: 'browse_category'
  get 'choose_category',                  to: 'home#choose_category',                         as: 'choose_category'
  get 'learn_more',                       to: 'home#learn_more',                              as: 'learn_more'

  # PDFs
  get 'research_participation',           to: 'home#research_participation_pdf',              as: 'research_participation'
  get 'research_participation_spanish',   to: 'home#research_participation_spanish_pdf',      as: 'research_participation_spanish'
  get 'bill_of_rights',                   to: 'home#bill_of_rights_pdf',                      as: 'bill_of_rights'
  get 'blood_draw',                       to: 'home#blood_draw_pdf',                          as: 'blood_draw'
  get 'blood_draw_spanish',               to: 'home#blood_draw_spanish_pdf',                  as: 'blood_draw_spanish'
  get 'genetic_research',                 to: 'home#genetic_research_pdf',                    as: 'genetic_research'
  get 'genetic_research_spanish',         to: 'home#genetic_research_spanish_pdf',            as: 'genetic_research_spanish'

  # Profile creation
  get  'age',                             to: 'profiles#get_age',                             as: 'age'
  post 'save_age',                        to: 'profiles#save_age',                            as: 'save_age'
  get  'healthy',                         to: 'profiles#get_healthy',                         as: 'healthy'
  post 'save_healthy',                    to: 'profiles#save_healthy',                        as: 'save_healthy'
  get  'categories',                      to: 'profiles#get_categories',                      as: 'categories'
  post 'save_categories',                 to: 'profiles#save_categories',                     as: 'save_categories'
  get  'email',                           to: 'profiles#get_email',                           as: 'email'
  post 'save_email',                      to: 'profiles#save_email',                          as: 'save_email'
  get 'profile_complete/:uuid',           to: 'profiles#profile_complete',                    as: 'profile_complete'
  get 'unsubscribe/:uuid',                to: 'profiles#unsubscribe',                         as: 'unsubscribe'

  # Admin
  post 'update_verified/:id',             to: 'admin#update_verified',                        as: 'update_verified'
  post 'update_category/:id',             to: 'admin#update_category',                        as: 'update_category'
  get 'edit_trials',                      to: 'admin#edit_trials',                            as: 'edit_trials'
  get 'edit_trial/:id',                   to: 'dartmouth_clinical_trials#edit',               as: 'edit_trial'
  get 'show_trial/:id',                   to: 'dartmouth_clinical_trials#show',               as: 'show_trial'
  post 'update_trial',                    to: 'dartmouth_clinical_trials#update',             as: 'update_trial'
  get 'admin',                            to: 'admin#index',                                  as: 'admin'  
  get 'search',                           to: 'admin#search',                                 as: 'search'
  post 'search_results',                  to: 'admin#search_results',                         as: 'search_results'
  post 'user_email',                      to: 'admin#user_email',                             as: 'user_email'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :auth_user

  def index
    if current_user.try(:admin?)
      redirect_to admin_path
    end
    @faqs = faqs
  end

  def browse
    @trials = browse_trials
  end

  def browse_healthy
    @trials = browse_trials
		@healthy = true
    render :browse
  end

  def browse_with_query
    @trials = browse_trials
    # If coming in from the landing page, there will be a passed-in query
    @query = ActionController::Base.helpers.sanitize params[:query]
    render :browse
  end

	def browse_category
    @trials = browse_trials
    @category = ActionController::Base.helpers.sanitize params[:category]
    render :browse
	end

  def choose_category
    @categories = DartmouthClinicalTrial.verified.recruiting.select(:category).distinct.order(:category).map {|trial| trial.category}
  end

  def learn_more
  end

  def research_participation_pdf
    send_pdf 'research_participation'
  end

  def research_participation_spanish_pdf
    send_pdf 'research_participation_spanish'
  end

  def bill_of_rights_pdf
    send_pdf 'bill_of_rights'
  end

  def blood_draw_pdf
    send_pdf 'blood_draw'
  end

  def blood_draw_spanish_pdf
    send_pdf 'blood_draw_spanish'
  end

  def genetic_research_pdf
    send_pdf 'genetic_research'
  end

  def genetic_research_spanish_pdf
    send_pdf 'genetic_research_spanish'
  end

  private

  def send_pdf(filename)
    send_file "#{Rails.root}/public/pdf/#{filename}.pdf", disposition: 'inline'
  end

  def browse_trials
    DartmouthClinicalTrial.recruiting.verified.order('created_at DESC, title ASC')
  end

  # TODO: Don't store these here
  def faqs
    [
      {
        question: "What is a clinical trial?",
          answer: "Clinical trials are experiments or observations done in clinical research. Such prospective biomedical or behavioral research studies on human participants are designed to answer specific questions about biomedical or behavioral interventions, including new treatments (such as novel vaccines, drugs, dietary choices, dietary supplements, and medical devices) and known interventions that warrant further study and comparison."
      },
      {
        question: "Why would I want to participate in a clinical trial?",
          answer: "People have different reasons. Mostly, It's the money."
      },
      {
        question: "Is this another question about clinical trials?",
          answer: "Yes, it most certainly is. You may find that there are even more questions below."
      },
      {
        question: "Does this seem to be the last question about clinical trials?",
          answer: "Absolutely. That is how things seem."
      },
      {
        question: "What is a clinical trial?",
          answer: "It's a pretty cool thing. Most people don't know about it."
      },
      {
        question: "What is a clinical trial?",
          answer: "It's a pretty cool thing. Most people don't know about it."
      },
      {
        question: "What is a clinical trial?",
          answer: "It's a pretty cool thing. Most people don't know about it."
      },
      {
        question: "What is a clinical trial?",
          answer: "It's a pretty cool thing. Most people don't know about it."
      }
    ]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_info_and_faqs.html.haml
.row#why-volunteer-and-faqs
  .col-sm-2
  .col-sm-4
    #why-volunteer
      %strong Why Volunteer in Clinical Research?
      %ul
        %li
          The development of new medical treatments and cures would be
          impossible without the active participation of research
          volunteers.
        %li
          By volunteering in a study, you will help others by contributing
          to medical research.
        %li
          You could also help researchers to learn about a disease or 
          condition.
        %li
          In some cases, you can try a new treatment before it is available
          outside of research studies; however, these new drugs, procedures,
          or devices may or may not be more effective than the ones that are
          already available.
  .col-sm-4
    #faqs
      %strong Frequently Asked Questions
      #faq-select
        = select_tag 'faq', options_for_select(@faqs.each_with_index.map {|faq, index| [faq[:question], index]})
      #faq-answer
  .col-sm-2

:javascript
  $(function() {
    // Set initial FAQs div size
    resizeFaqs();
    // Resize FAQs div when resizing window
    $(window).resize(function() {
      resizeFaqs();
    })
    // Initialize the FAQ answer to question #1
    displayFaqAnswer(0);
    // Update the FAQ answer when a new question is selected
    $('#faq').change(function(){
      displayFaqAnswer($('#faq').val());
    })
  })

  // Set the FAQ JSON
  var faqsJson = #{@faqs.to_json};

  // Keep the FAQS div the same height as the Why Volunteer div
  function resizeFaqs(){
    $('#faqs').height($('#why-volunteer').height());
  }

  // Display the FAQ answer with the passed-in index
  function displayFaqAnswer(index){
    $('#faq-answer').text(faqsJson[index]['answer']);
  }

app/views/home/_learn_more_link.html.haml
.row.background-dark-blue#more-about-row
  .col-sm-4.no-gutter
    %hr.gray-bar
  .col-sm-4.no-gutter{style: 'position:relative;'}
    = link_to 'Learn More About Volunteering for Research', learn_more_path, id: 'learn-more-bottom-link'
  .col-sm-4.no-gutter
    %hr.gray-bar

app/views/home/_search_and_links.html.haml
#banner-image
  .row#search-row
    .col-sm-2
    .col-sm-8
      %div
        %strong Search For Studies
      .form-group.has-feedback{style: 'padding-top:5px;'}
        %input#landing-page-query{type: 'text', class: 'form-control', placeholder: 'Search', autofocus: true}
        %i.fa.fa-search.form-control-feedback{style: 'padding-top:14px;color:#aaa;'}
      .hidden
        -# Hidden link. Query parameter is updated by JS and link click is simulated when user
        -# hits Enter in the search field
        = link_to '', browse_with_query_path('placeholder'), id: 'query-hidden-link'
    .col-sm-2
  .row#link-row
    .col-sm-2.no-gutter
    .col-sm-8.no-gutter
      .row.no-gutter
        .col-sm-4.small-left-gutter
          = link_to 'Sign Up to be Notified<br>About New Studies'.html_safe, age_path, class: 'landing-page-link'
        .col-sm-4
          = link_to 'Browse Open Studies<br>by Category'.html_safe, choose_category_path, class: 'landing-page-link'
        .col-sm-4.small-right-gutter
          = link_to 'Browse Healthy Volunteer<br>Studies'.html_safe, browse_healthy_path, class: 'landing-page-link'
    .col-sm-2.no-gutter

app/views/home/browse.html.haml
.body-container#browse-body
  .white Search:
  .row
    .col-sm-6.no-gutter
      %input#query{type: 'text', class: 'form-control', placeholder: 'Type here to search', value: @query, autofocus: true, autocomplete: 'off'}
  .white
    .filter
      Filter by category:
      .dropdown
        %button.btn#btn-categories.dropdown-toggle{type: 'button', "data-toggle" => 'dropdown'}
          %span#current-category= "All (#{@trials.length})"
          .fa.fa-chevron-down
        %ul.dropdown-menu
          %li= link_to "All (#{@trials.length})", '#', name: 'All', class: 'category-dropdown-link'
          - DartmouthClinicalTrial.categories.each do |category|
            - trial_count = DartmouthClinicalTrial.recruiting.where(category: category).count
            - if trial_count > 0 
              - category_str = "#{category} (#{trial_count})"
              %li= link_to category_str, '#', name: category, class: 'category-dropdown-link'
    .filter
      Only studies accepting:
      %button.btn#btn-healthy
        -# Use fa-check-square-o via JS when checked
        %span#healthy-check-box.fa.fa-square-o
        Healthy Volunteers
  .white#showing-trials-line
    Showing
    %strong.badge.bigger#matches= @trials.length
    of
    %strong.badge.bigger= @trials.length
    currently recruiting trials. Click on a trial for more information.
  .row#trial-table
    .col-xs-12.no-gutter
      %table.table.sorted-table
        %thead
          %tr
            %th.small Categories
            %th.small Study
          %tbody
            - @trials.each do |trial|
              %tr.title-row
                %td.small.category-cell
                  .badge.category-badge= trial.category
                  - if trial.healthy_volunteers
                    %br
                    .badge.healthy-badge Healthy Volunteers
                %td.trial.small.title-cell
                  %span.trial-chevron.fa.fa-chevron-circle-right 
                  = trial.title
              %tr.trial-details
                %td.trial.small.details-cell{colspan: 2}
                  %p
                    %strong Contact: 
                    = trial.contact_name ? "#{trial.contact_name}, " : nil
                    = mail_to (trial.contact_email || 'admin@engage.dartmouth.edu')
                    = trial.contact_phone ? ", #{trial.contact_phone} " : nil
                  %p
                    %strong Summary: 
                    = trial.summary
                  %p
                    %strong Gender:
                    = trial.gender
                  %p
                    %strong Minimum Age:
                    = trial.min_age || 'None'
                  %p
                    %strong Maximum Age:
                    = trial.max_age || 'None'
                  %p
                    %strong More Information:
                    = link_to trial.url, trial.url, target: '_blank'
:javascript
  var filterOnlyHealthy = false;
  var currentCategory = 'All';
  $(function() {
    // Place the cursor at the end of the input string
    $('#query').focus().val($('#query').val());
    // Apply the category filter if passed-in
    if(!"#{@category}" == '') {
      var categoryDropdownLink = $('[name="#{@category}"]')
      $('#current-category').text(categoryDropdownLink.text());
      currentCategory = "#{@category}"
    }
    // Apply healthy voluteers only filter if passed in
    if("#{@healthy}" == 'true') {
      $('#healthy-check-box').removeClass('fa-square-o').addClass('fa-check-square-o');
      filterOnlyHealthy = true;
    }
    // Run the search filter on page load in case there was a query or filter(s) passed it
    filterNow();
  })

app/views/home/choose_category.html.haml
.body-container
  #categories
    %p#categories-title Browse Studies By Category
    .row#categories-row
      - count = DartmouthClinicalTrial.verified.recruiting.where(healthy_volunteers: true).count
      .col-lg-4.small-gutter
        .category-link-container
          .hidden= link_to '', browse_healthy_path, class: 'hidden-link'
          .category-link Healthy Volunteer Studies
          .category-count= count
    - @categories.each_slice(3) do |slice|
      .row#categories-row
        - slice.each do |category|
          - count = category_count(category)
          .col-lg-4.small-gutter
            - if category
              .category-link-container
                .hidden= link_to '', browse_category_path(category), class: 'hidden-link'
                .category-link= category
                .category-count= count

app/views/home/index.html.haml
= render 'search_and_links'
= render 'info_and_faqs'
= render 'learn_more_link'

app/views/home/learn_more.html.haml
.body-container#learn-more-body
  .row
    .col-xs-12#learn-more-header Learn More About Volunteering for Research
  .row
    .col-md-5.no-gutter#learn-more-links
      %p.resources
        %strong Brochures
      %p.resources
        = link_to '<span class="resource-link">Research Participation</span><span class="fa fa-file-pdf-o"></span>'.html_safe,
          research_participation_path,
          target: '_blank'
        = link_to '(en Español)'.html_safe,
          research_participation_spanish_path,
          target: '_blank',
          class: 'resource-link'
      %p.resources
        = link_to '<span class="resource-link">Research Participant Bill of Rights</span><span class="fa fa-file-pdf-o"></span>'.html_safe,
          bill_of_rights_path,
          target: '_blank'
      %p.resources
        = link_to '<span class="resource-link">Common Research Procedures: Blood Draws</span><span class="fa fa-file-pdf-o"></span>'.html_safe,
          blood_draw_path,
          target: '_blank'
        = link_to '(en Español)'.html_safe,
          blood_draw_spanish_path,
          target: '_blank',
          class: 'resource-link'
      %p.resources
        = link_to '<span class="resource-link">Genetic Research</span><span class="fa fa-file-pdf-o"></span>'.html_safe,
          genetic_research_path,
          target: '_blank'
        = link_to '(en Español)'.html_safe,
          genetic_research_spanish_path,
          target: '_blank',
          class: 'resource-link'
      %p#external-links-title
        %strong External Links
      %p.resources
        = link_to '<span class="resource-link">The Center for Information and Study on Clinical Research Participation (CISCRP)</span><span class="fa fa-external-link"></span>'.html_safe,
          'https://www.ciscrp.org/',
          target: '_blank'
    .col-md-7.no-gutter#learn-more-image

app/views/home/offer_reactivate.html.haml
%h2 Welcome back.
%p Previously, you indicated that you would no longer like to recieve emails about research participation opportunities at Dartmouth-Hitchcock.
%p
  If you have changed you mind and would like to receive emails about these opportunities, 
  = link_to 'click here.', reactivate_path

app/views/home/thank_you.html.haml
%h2 Thank you for signing up!
%p You will be contacted by email from one of our staff if any studies that match your criteria are or become available.

app/views/home/welcome_back.html.erb
<h2>Welcome back.</h2>
<% if @user_selected.count ==0 %>
    <h3>Please complete your profile, select categories to subscribe.</h3>
<% end %>
<p>
Below is your volunteer profile.
<%= link_to 'Click here if you would like to change your profile.', edit_profile_path(@profile.id) %>
</p>

<p>  If you would no longer like to recieve emails about research participation oppportunities,
<%= link_to 'click here.', deactivate_path %></p>


<%= form_for(@category, url: create_diseases_path) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
  <% @a = 0 %>
  <div class="col-md-4">
  <%= f.collection_check_boxes(:name, Disease.all, :id, :title) do |b| %>
  <% @a = @a + 1 %>
  <% if @a < 20 %>
      <% if @user_selected.include?(Disease.find_by_title(b.text).id) %>
          <%= b.label { b.check_box(:checked=> true) + " "+b.text} %><br />
      <% else  %>
        <%= b.label { b.check_box + " "+b.text} %><br />
      <% end %>
   <% end %>
   <% end %>
  </div>
  <% @a = 0 %>
  <div class="col-md-4">
  <%= f.collection_check_boxes(:name, Disease.all, :id, :title) do |b| %>
  <% @a = @a + 1 %>
  <% if @a >= 20 and @a < 40 %>
      <% if @user_selected.include?(Disease.find_by_title(b.text).id) %>
        <%= b.label { b.check_box(:checked=> true) +" "+ b.text} %><br />
      <% else  %>
        <%= b.label { b.check_box + " "+ b.text} %><br />
      <% end %>
  <% end %>
  <% end %>
  </div>
  <% @a = 0 %>
  <div class="col-md-4">
  <%= f.collection_check_boxes(:name, Disease.all, :id, :title) do |b| %>
  <% @a = @a + 1 %>
  <% if @a >= 40 %>
      <% if @user_selected.include?(Disease.find_by_title(b.text).id) %>
        <%= b.label { b.check_box(:checked=> true) + b.text} %><br />
      <% else  %>
        <%= b.label { b.check_box + b.text} %><br />
      <% end %>
      <% end %>
  <% end %>
   </div>
  </div>

  <div class="actions" align="center">
      <%= f.submit :class => "btn btn-primary",:value => "Subscribe" %>
  </div>
<% end %>

app/views/home/welcome_back.html.haml
%h2 Welcome back.
%p
  Below is your volunteer profile.
  = link_to 'Click here if you would like to change your profile.', edit_profile_path(@profile.id)

%table
  %th Self or other
  %th Minors or adults
  %th Healthy volunteer
  %th Clinical category 1
  %th Clinical category 2
  %th Clinical category 3
  %tr
    %td= {false: 'other', true: 'self'}[@profile.self.to_s.to_sym]
    %td= @profile.ages 
    %td= {false: 'no', true: 'yes'}[@profile.healthy.to_s.to_sym]
    %td= @profile.chosen_category_1
    %td= @profile.chosen_category_2
    %td= @profile.chosen_category_3
%p
  If you would no longer like to recieve emails about research participation oppportunities, click 
  = link_to 'here.', deactivate_path

<div class="form_row">
  <label for="features[]">Features:</label>
    <br><%= check_box_tag 'features[]', 'scenarios' %> Scenarios
      <br><%= check_box_tag 'features[]', 'role_profiles' %> Role profiles
        <br><%= check_box_tag 'features[]', 'private_messages' %> Private messages
          <br><%= check_box_tag 'features[]', 'chatrooms' %> Chatrooms
            <br><%= check_box_tag 'features[]', 'forums' %> Forums
              <br><%= check_box_tag 'features[]', 'news' %> News
                <br><%= check_box_tag 'features[]', 'polls' %> Polls
                  </div>