config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  # Landing page and browsing
  root 'home#index'
  get 'browse',                           to: 'home#browse',                                  as: 'browse'
  get 'browse_healthy',                   to: 'home#browse_healthy',                          as: 'browse_healthy'
  get 'browse_with_query/:query',         to: 'home#browse_with_query',                       as: 'browse_with_query'
  get 'browse_category/:category',        to: 'home#browse_category',                         as: 'browse_category'
  get 'choose_category',                  to: 'home#choose_category',                         as: 'choose_category'
  get 'learn_more',                       to: 'home#learn_more',                              as: 'learn_more'

  # PDFs
  get 'research_participation',           to: 'home#research_participation_pdf',              as: 'research_participation'
  get 'research_participation_spanish',   to: 'home#research_participation_spanish_pdf',      as: 'research_participation_spanish'
  get 'bill_of_rights',                   to: 'home#bill_of_rights_pdf',                      as: 'bill_of_rights'
  get 'blood_draw',                       to: 'home#blood_draw_pdf',                          as: 'blood_draw'
  get 'blood_draw_spanish',               to: 'home#blood_draw_spanish_pdf',                  as: 'blood_draw_spanish'
  get 'genetic_research',                 to: 'home#genetic_research_pdf',                    as: 'genetic_research'
  get 'genetic_research_spanish',         to: 'home#genetic_research_spanish_pdf',            as: 'genetic_research_spanish'

  # Profile creation
  get  'age',                             to: 'profiles#get_age',                             as: 'age'
  post 'save_age',                        to: 'profiles#save_age',                            as: 'save_age'
  get  'healthy',                         to: 'profiles#get_healthy',                         as: 'healthy'
  post 'save_healthy',                    to: 'profiles#save_healthy',                        as: 'save_healthy'
  get  'categories',                      to: 'profiles#get_categories',                      as: 'categories'
  post 'save_categories',                 to: 'profiles#save_categories',                     as: 'save_categories'
  get  'email',                           to: 'profiles#get_email',                           as: 'email'
  post 'save_email',                      to: 'profiles#save_email',                          as: 'save_email'
  get 'profile_complete/:uuid',           to: 'profiles#profile_complete',                    as: 'profile_complete'
  get 'unsubscribe/:uuid',                to: 'profiles#unsubscribe',                         as: 'unsubscribe'

  # Admin
  post 'update_verified/:id',             to: 'admin#update_verified',                        as: 'update_verified'
  post 'update_category/:id',             to: 'admin#update_category',                        as: 'update_category'
  get 'edit_trials',                      to: 'admin#edit_trials',                            as: 'edit_trials'
  get 'edit_trial/:id',                   to: 'dartmouth_clinical_trials#edit',               as: 'edit_trial'
  get 'show_trial/:id',                   to: 'dartmouth_clinical_trials#show',               as: 'show_trial'
  post 'update_trial',                    to: 'dartmouth_clinical_trials#update',             as: 'update_trial'
  get 'admin',                            to: 'admin#index',                                  as: 'admin'  
  get 'search',                           to: 'admin#search',                                 as: 'search'
  post 'search_results',                  to: 'admin#search_results',                         as: 'search_results'
  post 'user_email',                      to: 'admin#user_email',                             as: 'user_email'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception

  # Authenticate for all actions by default
  # before_action :auth_user

  def auth_user
    redirect_to new_profile_path unless (user_signed_in? or params[:controller].include? 'devise')
  end

  def only_admins
    redirect_to root unless current_user && current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def star
		content_tag :span, '*', style: 'color:red;'
	end

  def category_count(category)
    return nil unless category
    DartmouthClinicalTrial.recruiting.where(category: category).count
  end

end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'favicon/apple-touch-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path 'favicon/apple-touch-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'favicon/apple-touch-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'favicon/apple-touch-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path 'favicon/apple-touch-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'favicon/apple-touch-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path 'favicon/apple-touch-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'favicon/apple-touch-icon-152x152.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-96x96.png' %>" sizes="96x96">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="<%= asset_path 'favicon/mstile-144x144.png' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/application/_footer.html.haml
%footer.navbar-fixed-bottom#footer
  .row#footer
    .col-sm-4
    .col-sm-2.footer-link#left-footer-link
      = link_to 'Dartmouth SYNERGY', 'https://synergy.dartmouth.edu/', class: 'footer-link-text'
    .col-sm-2.footer-link
      = link_to 'Dartmouth-Hitchcock', 'http://www.dartmouth-hitchcock.org/', class: 'footer-link-text'
    .col-sm-4

app/views/application/_head.html.haml
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{charset: "utf-8"}/
%meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
%title= content_for?(:title) ? yield(:title) : 'Engage'
%link{:href => "https://www.google.com/fonts#UsePlace:use/Collection:Source+Sans+Pro", :rel => "stylesheet", :type => "text/css"}
= csrf_meta_tags
/ Le HTML5 shim, for IE6-8 support of HTML elements
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
= stylesheet_link_tag "application", :media => "all"
= favicon_link_tag 'favicon.png', :rel => 'shortcut icon'
= javascript_include_tag "application"

app/views/application/_navbar.html.haml
.container-fluid{style: 'padding:10px;background-color:white;'}
  = link_to image_tag('engage_logo', height: '50'), root_path
  = link_to image_tag('participate_in_research', height: '30'), root_path, style: 'padding-left:10px;', id: 'participate-in-research'
  %div{style: 'float:right;height:30px;'}
    %div{style: 'margin-top:15px;'}
      - if user_signed_in?
        Logged in as 
        = link_to current_user.email, edit_user_registration_path
      - else
        = link_to 'Learn More', learn_more_path

- if user_signed_in? || (params[:controller] == 'devise/sessions' && params[:action] == 'new')
  .clearfix
    %nav.navbar.navbar-dark.no-radius{style: 'background-color:#333;border:none;'}
      .container
        %ul.nav.navbar-nav.navbar-left
          - if user_signed_in?
            - if current_user.admin?
              %li.nav-item
                = link_to 'Dashboard', root_path, class: 'navbar-link first'
              %li.nav-item
                = link_to 'Search Trials', search_path, class: 'navbar-link first'
              %li.nav-item
                = link_to 'Edit Trials', edit_trials_path, class: 'navbar-link first'
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li.nav-item
              = link_to 'Log Out', destroy_user_session_path, method: 'delete', class: 'navbar-link last'
          - else
            -#  %li.nav-item
            -#    = link_to 'Register', new_profile_path, class: 'navbar-link last'
            -# %li.nav-item
            -#   = link_to 'Login', new_user_session_path, class: 'navbar-link last'